# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-js-build

on:
  push:
    branches: [ master ]
    paths:
      - 'js/src/**'
      - 'js/package.json'
      - 'js/package-lock.json'
      - 'js/tsconfig.json'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM build/test
      working-directory: js
      run: |
          npm ci
          npm run build --if-present
          npm test

#    - name: Switch to 'dist' branch
#      uses: actions/checkout@v2
#      with:
#        ref: dist
#        clean: false
#
#    - name: Push the transpiling-output code to dist branch
#      working-directory: js
#      run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          chmod +x ./release.sh
#          bash ./release.sh
